OrakulasRedirectBundle:
    resource: "@OrakulasRedirectBundle/Resources/config/routing.yml"
    prefix:   /redirect

OrakulasExcelBundle:
    resource: "@OrakulasExcelBundle/Resources/config/routing.yml"
    prefix:   /

OrakulasMainBundle:
    resource: "@OrakulasMainBundle/Resources/config/routing.yml"
    prefix:   /

OrakulasModelBundle:
    resource: "@OrakulasModelBundle/Resources/config/routing.yml"
    prefix:   /model

login:
    pattern: /login
    defaults: { _controller: OrakulasSecurityBundle:Security:login }

check_login:
    pattern: /check_login

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
