OrakulasMainBundle:
    resource: "@OrakulasMainBundle/Resources/config/routing.yml"
    prefix:   /

OrakulasModelBundle:
    resource: "@OrakulasModelBundle/Resources/config/routing.yml"
    prefix:   /model

login:
    pattern: /login
    defaults: { _controller: OrakulasSecurityBundle:Security:login }

login_check:
    pattern: /check__if_login

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
