security:
    firewalls:
        login_firewall:
            pattern: ^/login$
            anonymous: ~
        secured_area:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout: ~

#    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        main:
            entity: { class: Orakulas\ModelBundle\Entity\User, property: username }

    encoders:
        Orakulas\ModelBundle\Entity\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: false
