security:
    firewalls:
    #    login_firewall:
    #       pattern: ^/login$
    #       anonymous: ~

        ajax_calls:
            pattern:    ^/_wdt
            anonymous:  ~
        secured_area:
            pattern: ^/(?!login)
            form_login:
                login_path: /login
                check_path: /check_login
            logout: ~

    access_control:
        - { path: ^/_wdt, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        main:
            entity: { class: Orakulas\ModelBundle\Entity\User, property: username }

    encoders:
        Orakulas\ModelBundle\Entity\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: false
