OrakulasModelBundle_departmentsLoad_view:
    pattern: /view
    defaults: { _controller: OrakulasModelBundle:DepartmentLoad:view }
    requirements:
      _method:  GET

OrakulasModelBundle_departmentsLoad_viewFullDate:
    pattern: /viewFullDate
    defaults: { _controller: OrakulasModelBundle:DepartmentLoad:viewFullDate }
    requirements:
      _method:  GET
