OrakulasModelBundle_departments_create:
    pattern: /create
    defaults: { _controller: OrakulasModelBundle:Department:create }
    requirements:
      _method:  POST

OrakulasModelBundle_departments_read:
    pattern: /read
    defaults: { _controller: OrakulasModelBundle:Department:read }
    requirements:
      _method:  GET

OrakulasModelBundle_departments_update:
   pattern: /update
   defaults: { _controller: OrakulasModelBundle:Department:update }
   requirements:
     _method:  POST

OrakulasModelBundle_departments_delete:
    pattern: /delete
    defaults: { _controller: OrakulasModelBundle:Department:delete }
    requirements:
      _method:  POST

OrakulasModelBundle_departments_usedInfoSys:
    pattern: /usedInfoSys
    defaults: { _controller: OrakulasModelBundle:Department:usedInfoSys }
    requirements:
      _method: POST

OrakulasModelBundle_departments_administeredSupportTypes:
    pattern: /administeredSupportTypes
    defaults: { _controller: OrakulasModelBundle:Department:administeredSupportTypes }
    requirements:
      _method: POST