OrakulasModelBundle_departmentInfoSysUsages_create:
    pattern: /create
    defaults: { _controller: OrakulasModelBundle:DepartmentInfoSysUsage:create }
    requirements:
      _method:  POST

OrakulasModelBundle_departmentInfoSysUsages_read:
    pattern: /read
    defaults: { _controller: OrakulasModelBundle:DepartmentInfoSysUsage:read }
    requirements:
      _method:  GET

OrakulasModelBundle_departmentInfoSysUsages_update:
   pattern: /update
   defaults: { _controller: OrakulasModelBundle:DepartmentInfoSysUsage:update }
   requirements:
     _method:  POST

OrakulasModelBundle_departmentInfoSysUsages_delete:
    pattern: /delete
    defaults: { _controller: OrakulasModelBundle:DepartmentInfoSysUsage:delete }
    requirements:
      _method:  POST