OrakulasModelBundle_isLoad_view:
    pattern: /view
    defaults: { _controller: OrakulasModelBundle:isLoad:view }
    requirements:
      _method:  GET

OrakulasModelBundle_isLoad_viewFullDate:
    pattern: /viewFullDate
    defaults: { _controller: OrakulasModelBundle:isLoad:viewFullDate }
    requirements:
      _method:  GET
