OrakulasModelBundle_supportTypes_create:
    pattern: /create
    defaults: { _controller: OrakulasModelBundle:SupportType:create }
    requirements:
      _method:  POST

OrakulasModelBundle_supportTypes_read:
    pattern: /read
    defaults: { _controller: OrakulasModelBundle:SupportType:read }
    requirements:
      _method:  GET

OrakulasModelBundle_supportTypes_update:
   pattern: /update
   defaults: { _controller: OrakulasModelBundle:SupportType:update }
   requirements:
     _method:  POST

OrakulasModelBundle_supportTypes_delete:
    pattern: /delete
    defaults: { _controller: OrakulasModelBundle:SupportType:delete }
    requirements:
      _method:  POST