OrakulasModelBundle_supportAdministrationTimes_create:
    pattern: /create
    defaults: { _controller: OrakulasModelBundle:SupportAdministrationTime:create }
    requirements:
      _method:  POST

OrakulasModelBundle_supportAdministrationTimes_read:
    pattern: /read
    defaults: { _controller: OrakulasModelBundle:SupportAdministrationTime:read }
    requirements:
      _method:  GET

OrakulasModelBundle_supportAdministrationTimes_update:
   pattern: /update
   defaults: { _controller: OrakulasModelBundle:SupportAdministrationTime:update }
   requirements:
     _method:  POST

OrakulasModelBundle_supportAdministrationTimes_delete:
    pattern: /delete
    defaults: { _controller: OrakulasModelBundle:SupportAdministrationTime:delete }
    requirements:
      _method:  POST