OrakulasModelBundle_homepage:
    pattern:  /
    defaults: { _controller: OrakulasModelBundle:Default:index }

OrakulasModelBundle_allCategories:
    pattern:  /categories
    defaults: { _controller: OrakulasModelBundle:Default:allCategories }
