OrakulasModelBundle_departments:
    resource: "@OrakulasModelBundle/Resources/config/entities/departmentRouting.yml"
    prefix:   /departments

OrakulasModelBundle_departmentInfoSysUsages:
    resource: "@OrakulasModelBundle/Resources/config/entities/departmentInfoSysUsageRouting.yml"
    prefix:   /departmentInfoSysUsages

OrakulasModelBundle_informationalSystems:
    resource: "@OrakulasModelBundle/Resources/config/entities/informationalSystemRouting.yml"
    prefix:   /informationalSystems

OrakulasModelBundle_supportAdministrationTimes:
    resource: "@OrakulasModelBundle/Resources/config/entities/supportAdministrationTimeRouting.yml"
    prefix:   /supportAdministrationTimes

OrakulasModelBundle_supportCategories:
    resource: "@OrakulasModelBundle/Resources/config/entities/supportCategoryRouting.yml"
    prefix:   /supportCategories

OrakulasModelBundle_supportHistories:
    resource: "@OrakulasModelBundle/Resources/config/entities/supportHistoryRouting.yml"
    prefix:   /supportHistories

OrakulasModelBundle_supportType:
    resource: "@OrakulasModelBundle/Resources/config/entities/supportTypeRouting.yml"
    prefix:   /supportTypes

OrakulasModelBundle_users:
    resource: "@OrakulasModelBundle/Resources/config/entities/userRouting.yml"
    prefix:   /users

OrakulasModelBundle_departmentsLoad:
    resource: "@OrakulasModelBundle/Resources/config/entities/departmentLoadRouting.yml"
    prefix:   /departmentsLoad