parameters:
#    orakulas_security.example.class: Orakulas\SecurityBundle\Example

services:
    authentication_handler:
        class: Orakulas\SecurityBundle\Handlers\AuthenticationHandler
       #class: %orakulas_security.example.class%


#    orakulas_security.example:
#        class: %orakulas_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
