TempSupportHistory:
  type: entity
  table: temp_support_history
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    supportTypeCode:
      type: string
      length: 20
      fixed: false
      nullable: false
      column: support_type_code
    startDate:
      type: date
      nullable: false
      column: start_date
    endDate:
      type: date
      nullable: false
      column: end_date
    supportRequestCount:
      type: integer
      unsigned: false
      nullable: false
      column: support_request_count
  lifecycleCallbacks: {  }
