TempDepartmentInfoSysUsage:
  type: entity
  table: temp_department_info_sys_usage
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    createdTimestamp:
      type: datetime
      nullable: false
      column: created_timestamp
    updatedTimestamp:
      type: datetime
      nullable: false
      column: updated_timestamp
    infoSysCode:
      type: string
      length: 20
      fixed: false
      nullable: false
      column: info_sys_code
    departmentCode:
      type: string
      length: 20
      fixed: false
      nullable: false
      column: department_code
  lifecycleCallbacks: {  }
