Orakulas\ModelBundle\Entity\Department:
  type: entity
  table: department
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    code:
      type: string
      length: 20
      fixed: false
      nullable: false
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
  manyToMany:
    informationalSystems:
      targetEntity: InformationalSystem
      inversedBy: departments
      joinTable:
        name: department_info_sys_usage
        joinColumns:
          department_id:
            referencedColumnName: id
        inverseJoinColumns:
          informational_system_id:
            referencedColumnName: id
  lifecycleCallbacks: {  }
