OrakulasRedirectBundle_lang:
    pattern:  /{lang}
    defaults: { _controller: OrakulasRedirectBundle:Redirect:redirect }

OrakulasRedirectBundle_home:
    pattern:  /
    defaults: { _controller: OrakulasRedirectBundle:Redirect:redirect }