parameters:
#    orakulas_redirect.example.class: Orakulas\RedirectBundle\Example

services:
#    orakulas_redirect.example:
#        class: %orakulas_redirect.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
