OrakulasExcelBundle_import_support_histories:
    pattern:  /excel/import/supportHistories
    defaults: { _controller: OrakulasExcelBundle:Import:readSupportHistories }

OrakulasExcelBundle_export:
    pattern: /excel/export
    defaults: { _controller: OrakulasExcelBundle:Export:exportData }

OrakulasExcelBundle_save_png:
    pattern:  /excel/savePng
    defaults: { _controller: OrakulasExcelBundle:SavePng:savePng }

OrakulasExcelBundle_download:
    pattern:  /excel/download/{filename}
    defaults: { _controller: OrakulasExcelBundle:Download:download }
