parameters:
#    orakulas_excel.example.class: Orakulas\ExcelBundle\Example

services:
#    orakulas_excel.example:
#        class: %orakulas_excel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
